title: Explaining Black Holes
description: A public outreach comics project
theme: jekyll-theme-cayman
#  logo: /images/Carlsberg-Mindelegat-Green-RGB-DK.png
show_downloads: false
github:
  is_project_page: false
